Xilinx/finn

- src/finn/transformation/batchnorm_to_affine.py
I think the intent of removing producer and consumer was limited to the squeeze and unsqueeze nodes but in reality the function was removing them in any case.
this should fix #43
> [fix]  batchnorm transform always removes producer and consumer nodes

- src/finn/custom_op/fpgadataflow/convolutioninputgenerator.py
- src/finn/custom_op/fpgadataflow/streamingdatawidthconverter_batch.py
- src/finn/custom_op/fpgadataflow/streamingfclayer_batch.py
- src/finn/custom_op/fpgadataflow/streamingmaxpool_batch.py
- src/finn/util/fpgadataflow.py
PyVerilator is not supported on Windows. I think, while it makes sense to keep it as a required dependency, it would be good to be able to deal with its absence in an ordered manner. 
This is required to support Brevitas-FINN tests on Windows.
> Deal gracefully with missing PyVerilator

- src/finn/transformation/__init__.py
- src/finn/transformation/fpgadataflow/hlssynth_ipgen.py
Hi,
here is my current implementation for the `NodeLocalTransformation` and the updated `HLSSynth_IPGen`, which now subclasses `NodeLocalTransformation`.
By default all operations still run in serial, because I have noticed that there is a case where the synthesis will overshoot the 16 GB memory mark when working on the LFC network. And this already happens for only two threads. See this plot:
On some systems, as my desktop system this is not a problem, but my laptop would then forcefully kill the vivado process, which caused errors later down the line.
So for now the default is set such that one needs to consciously enable parallelization.
> Support for node-local transformations

- src/finn/transformation/general.py
Make every parameter tensor unique. The aim is to avoid affecting other nodes apart from the one a transformation is operating on.
Several nodes can point to the same parameter tensor if an instance of a Pytorch module is used multiple times.
Passing new test in tests/transformation/test_general_transformation.py
> Add new transformation to give unique parameter tensors

- src/finn/core/modelwrapper.py
- tests/core/test_modelwrapper.py
Add utility functions to set and get sparsity annotation of a tensor. Integrate unit test of new functions into modelwrapper test.
> [Core & Test] Add modelwrapper functions to get and set sparsity annotation

- src/finn/transformation/fpgadataflow/prepare_cppsim.py
Parallel version of `PrepareCppSim` not using `NodeLocalTransformation` as access to model info is needed.
`NodeLocalTransformation` could be modified to allow read-only access to model.
**Test:** Passes test_convert_to_hls_layers_cnv.py
> [FPGADataFlow] Create parallel version of PrepareCppSim

- src/finn/util/basic.py
Add env variable to set the threshold for max error in rounding for finn execution. Default is 1e-2.
> [Util] Error threshold for max error in rounding for finn execution as env var

- src/finn/custom_op/fpgadataflow/tlastmarker.py
- src/finn/transformation/fpgadataflow/insert_tlastmarker.py
Added a number of features to the tlast marker:
- ability to use static or dynamic number of iterations. Dynamic is the default, and creates a axilite interface. static does not create an interface and uses the number of iterations specified in the attribute of the same name
- ability to use qdma_axis or ap_axiu for the stream interfaces. While they don't seem to differ, Vitis documentation makes a point of specifying that qdma_axis is to be used for streaming connections to the host, while ap_axiu is for kernel-to-kernel streaming
- ability to remove tlast instead of inserting it, if specified a "in" direction
These changes make the tlastmarker generally useful as a stream adapter for kernel to kernel/host communication in Vitis.
Depends on: #146 weakly, since the IODMA op name is …
> Added features to tlastmarker and updated the insertion transform

- src/finn/custom_op/fpgadataflow/iodma.py
- src/finn/transformation/fpgadataflow/insert_iodma.py
Added a custom hls op what implements DMA functionality from the hlslib dma.h:
- input dma
- output dma
- wrapping dma, required for e.g. weight streaming from external memory
Note: simulation is not implemented for this node as it's unclear how to fit it within the stream in / stream out simulation harness. Open to suggestions on this. Also, there are no unit tests in this PR but a test will be submitted for multiple aspects of Vitis integration later on.
> Added custom hls op for DMA node, and transform to insert it

- src/finn/custom_op/fpgadataflow/streamingfclayer_batch.py
- tests/fpgadataflow/test_fpgadataflow_fclayer.py
This PR implements external weights for StreamingFCLayer - similar to decoupled, but instead of the streamer being embedded into the layer, it is assumed external.
Depends on #186 because it calls `super().get_verilog_top_module_intf_names()`
> Added external weights option to StreamingFCLayer

- src/finn/transformation/streamline/reorder.py
New transform `MoveScalarLinearPastInvariants` to move linear ops past "GlobalAveragePool" ,"Reshape" ,"Transpose" and "Flatten"
- Lucian's code
- It was needed when our use case used "GlobalAveragePool" instead of "QuantAvPool". Non needed for this case anymore.
> [Transformation] New transform to move linear ops past several ops

- src/finn/transformation/fpgadataflow/make_pynq_driver.py
- src/finn/transformation/fpgadataflow/templates.py
Provides a path to driver generation for Alveo builds, where it has to be called before IODMA insertion, so I changed the missing pynq project from an exception to a warning.
This transform hasn't been tested yet on zynq or alveo. I'm hoping that by submitting the PR it will get tested on Zynq by the regression test.
> Updated driver generation transform and template

- notebooks/end2end_example/tfc_end2end_example.ipynb
- src/finn/core/rtlsim_exec.py
- src/finn/core/throughput_test.py
- src/finn/custom_op/fpgadataflow/__init__.py
- src/finn/transformation/fpgadataflow/annotate_cycles.py
- tests/end2end/test_zynqbuild_end2end_cnv_w1a1.py
- tests/fpgadataflow/test_convert_to_hls_conv_layer.py
- tests/fpgadataflow/test_convert_to_hls_pool_batch.py
- tests/fpgadataflow/test_fpgadataflow_addstreams.py
- tests/fpgadataflow/test_fpgadataflow_channelwise_ops.py
- tests/fpgadataflow/test_fpgadataflow_convinputgenerator.py
- tests/fpgadataflow/test_fpgadataflow_duplicatestreams.py
- tests/fpgadataflow/test_fpgadataflow_fclayer.py
- tests/fpgadataflow/test_fpgadataflow_fmpadding.py
- tests/fpgadataflow/test_fpgadataflow_globalaccpool.py
- tests/fpgadataflow/test_fpgadataflow_thresholding.py
- tests/fpgadataflow/test_layer_streaming_maxpool_batch.py
Adds `AnnotateCycles` transform, which does what the `exp_cycles_per_layer` analysis pass does, but instead of returning a dict it annotates each node (adds an `cycles_estimated` attribute). Also recurses into StreamingDataflowPartitions.
> Cycle estimation annotation transform

- docker/quicktest.sh
- src/finn/core/modelwrapper.py
- src/finn/custom_op/fpgadataflow/streamingfclayer_batch.py
- src/finn/transformation/fpgadataflow/create_dataflow_partition.py
- src/finn/transformation/general.py
- src/finn/transformation/merge_onnx_models.py
- src/finn/util/basic.py
- tests/fpgadataflow/test_convert_to_hls_layers_fc.py
Introduce some clean-up transforms (remove unused tensors, static inputs and sort graph) after every applied transform, can be disabled by setting the optional argument `model.transform(trn(), cleanup=False)`
> Post transform cleanups

- docker/finn_entrypoint.sh
- src/finn/util/pytorch.py
- tests/brevitas/test_brevitas_avg_pool_export.py
- tests/brevitas/test_brevitas_debug.py
- tests/brevitas/test_brevitas_relu_act_export.py
Move to the new Brevitas export flow (see https://github.com/Xilinx/brevitas/pull/187) to keep up-to-date and take advantage of new features. Current version in the PR passes the whole FINN test, but need to check a few more things since this is a reasonably big change:
> Move to new Brevitas export flow

- docker/Dockerfile.finn_dev
- finn-rtllib/memstream/component.xml
Added design files for use in simulation as well.  Vivado behavioral sim is otherwise unable to find the memstream IP during compilation.
Note this was done using version 2020.1 while previous ip was packaged with 2019.1.3
> Memstream ip fix

- .gitignore
- docker/Dockerfile.finn_ci
- docker/Dockerfile.finn_dev
- requirements.txt
- src/finn/core/onnx_exec.py
- src/finn/custom_op/fpgadataflow/labelselect_batch.py
- src/finn/custom_op/fpgadataflow/thresholding_batch.py
- src/finn/transformation/fpgadataflow/convert_to_hls_layers.py
- src/finn/transformation/fpgadataflow/create_stitched_ip.py
- src/finn/transformation/fpgadataflow/make_pynq_driver.py
- src/finn/transformation/fpgadataflow/templates.py
- src/finn/transformation/infer_data_layouts.py
- src/finn/transformation/streamline/absorb.py
- src/finn/transformation/streamline/reorder.py
- src/finn/util/gdrive.py
- src/finn/util/test.py
- tests/end2end/test_end2end_bnn_pynq.py
- tests/fpgadataflow/test_convert_to_hls_layers_synthetic.py
- tests/fpgadataflow/test_fpgadataflow_thresholding.py
- tests/transformation/test_absorb_mul_into_topk.py
Previously the FINN end2end examples (BNN-PYNQ networks, TFC/SFC/LFC and CNV) were set up in such a way that a few layers were still outside the dataflow partition (i.e. not converted to HLS). Due to our lacking heterogeneous execution model this resulted in big performance penalties when doing top-1 validation on the dataset, and just using the networks in general.
Using a combination of the network updates pushed to latest Brevitas, additional input preprocessing + quantization information and an additional Top-1 layer at the end, this PR moves all the end-to-end examples to be fully on the FPGA.
Also adds preliminary support for posting end2end results to a Google Drive dashboard.
> Move end2end examples to be fully on-FPGA

- src/finn/custom_op/fpgadataflow/streamingfclayer_batch.py
- tests/fpgadataflow/test_runtime_weights.py
Introduce a `make_weight_file` function to `StreamingFCLayer_Batch` that can be called both for regular codegen as well as for generating weight files for runtime-writable weights.
> Runtime weight utils

- src/finn/custom_op/fpgadataflow/templates.py
- src/finn/custom_op/fpgadataflow/thresholding_batch.py
- src/finn/transformation/fpgadataflow/convert_to_hls_layers.py
- tests/fpgadataflow/test_fpgadataflow_thresholding.py
Introduce a decoupled variant of the standalone thresholding layer, using the same `memstream` component as the decoupled `StreamingFCLayer` to separte compute and memory. Supports runtime-writable thresholds.
> Decoupled and runtime-writable thresholds

- docker/Dockerfile.finn_ci
- docker/Dockerfile.finn_dev
- docker/finn_entrypoint.sh
- requirements.txt
- run-docker.sh
- setup.cfg
`finn-base` is available through PyPI and pip-installable, and the intention is to do the same for this repository one day. This PR sets up `setup.cfg` and dependency handling in a slightly better way for the future.
> Future-proofing pypi/pip installability

- src/finn/custom_op/fpgadataflow/streamingdatawidthconverter_batch.py
Partitions are assembled in bd. If the input of a bd is a vivado lib datawidth converted and its parameter `CONFIG.S_TDATA_NUM_BYTES.VALUE_SRC`  is set to `PROPAGATED`, the actual input width information is lost and the partition assumes an input width of 1 byte which probably will cause a bottleneck.
Set vivado DWC input width explicitly
> Partition input vivado DWC bugfix

- src/finn/transformation/fpgadataflow/create_stitched_ip.py
After synth, the tcl stript for stitched kernel generates a human readable utilization report
> [FPGADATAFLOW] Add report_utilization to stitched project tcl script

- docs/finn/command_line.rst
- src/finn/builder/build_dataflow_config.py
- src/finn/builder/build_dataflow_steps.py
For `build_dataflow`, seperate out the HLS code generation and IP synthesis as two different steps. This allows running the build flow to target HLS code generation only without any synthesis, in a way this is the "last exit before toll" for large or highly-unfolded networks where even HLS IP gen takes a long time.
> Separate HLS codegen and ipgen steps

- src/finn/transformation/fpgadataflow/templates.py
The ZCU102 board is officially supported, but the board part setting was missing in the respective Tcl script template.
> Fix ZCU102 support in Vivado shell project

- src/finn/transformation/streamline/__init__.py
- src/finn/transformation/streamline/reorder.py
- tests/transformation/streamline/test_move_mul_past_maxpool.py
Adds a reordering transformation to move (non-negative) scalar or channelwise multiplications past 2D MaxPool nodes.
This improves the model compatibility of streamlining, e.g. in the case of a bnn_pynq/cnv_w4a4 network (issue #279).
> Add MoveMulPastMaxPool transformation to streamlining

- src/finn/transformation/fpgadataflow/insert_iodma.py
In some cases, this bug caused an erroneous `intfWidth` setting of the input IODMA, resulting in a significant performance regression for memory-bound accelerators.
> Fix IODMA interface width selection

- docker/quicktest.sh
- docs/finn/getting_started.rst
- notebooks/end2end_example/bnn-pynq/cnv_end2end_example.ipynb
- notebooks/end2end_example/bnn-pynq/tfc_end2end_example.ipynb
- setup.cfg
- src/finn/custom_op/fpgadataflow/tlastmarker.py
- src/finn/transformation/fpgadataflow/make_deployment.py
- ssh_keys/config.bak
- tests/end2end/test_end2end_access_board.py
- tests/end2end/test_end2end_cybsec_mlp.py
- tests/end2end/test_ext_weights.py
ssh publickey auth is now the recommended method for accessing PYNQ boards, with steps in the documentation describing how to set this up.
> Changes to board access for end2end tests

- docker/Dockerfile.finn_ci
- docker/Dockerfile.finn_dev
- docker/finn_entrypoint.sh
- src/finn/transformation/fpgadataflow/floorplan.py
- src/finn/transformation/fpgadataflow/vitis_build.py
Currently FINN ops take attributes for SLR and memory bank but these are not applied when linking. This PR fixes this and adds some reasonable defaults for memory bank assignment when no explicit value has been requested. Because of this last change, this PR makes #246 redundant.
@maltanar I've added finn-experimental because I test this in conjunction with the partitioner. The changes here don't require finn-experimental.
> [VitisBuild] Apply SLR and memory bank constraints during Vitis Linking

- src/finn/custom_op/fpgadataflow/fmpadding_batch.py
- tests/fpgadataflow/test_fpgadataflow_fmpadding.py
Changed FMPadding_Batch operation and test case.
This PR is part of a series of PRs. An overview of the (priority - repository - PR# - description) is given below:
1 -- finn-base -- Xilinx/finn-base#29 -- support for non-equal dilation
2 -- finn -- #320 -- compatibility with latest finn-base changes.
Note that the FINN-base commit is be changed to point to the latest commit (Xilinx/finn-base#29) for the PRs following in this series: [here_finnbase](https://github.com/Xilinx/finn/blob/af783db8dc2a1d2e95bd569d39464b935520b6d2/docker/finn_entrypoint.sh#L15).
Besides, the FINN-hlslib commit pointer must be changed to (at least) 5c45a41a755bca534ba737e1b54ec9bbddf42a41 [here_finn_hlslib](https://github.com/Xilinx/finn/blob/af783db8dc2a1d2e95bd569d39464b935520b6d2/docker/finn_entrypoint.sh#L18) …
> Support for non-square images FMPadding_Batch

- src/finn/custom_op/fpgadataflow/vector_vector_activate_batch.py
- tests/fpgadataflow/test_fpgadataflow_vvau.py
Changed Vector_Vector_Activate_Batch operation and added a test case.
This PR is part of a series of PRs. An overview of the (priority - repository - PR# - description) is given below:
1 -- finn-base -- Xilinx/finn-base#29 -- support for non-equal dilation
2 -- finn -- #320 -- compatibility with latest finn-base changes.
Note that the FINN-base commit is be changed to point to the latest commit (Xilinx/finn-base#29) for the PRs following in this series: [here_finnbase](https://github.com/Xilinx/finn/blob/af783db8dc2a1d2e95bd569d39464b935520b6d2/docker/finn_entrypoint.sh#L15).
Besides, the FINN-hlslib commit pointer must be changed to (at least) 5c45a41a755bca534ba737e1b54ec9bbddf42a41 [here_finn_hlslib](https://github.com/Xilinx/finn/blob/af783db8dc2a1d2e95bd569d39464b935520b6d2/docker/fin …
> Added support for non-square images Vector_Vector_Activate_Batch

- src/finn/custom_op/fpgadataflow/__init__.py
- src/finn/custom_op/fpgadataflow/convolutioninputgenerator1d.py
- tests/fpgadataflow/test_fpgadataflow_convinputgenerator1d.py
Added new custom_op for 1D convolutions and a test case.
This PR is part of a series of PRs. An overview of the (priority - repository - PR# - description) is given below:
1 -- finn-base -- Xilinx/finn-base#29 -- support for non-equal dilation
2 -- finn -- #320 -- compatibility with latest finn-base changes.
Note that the FINN-base commit is be changed to point to the latest commit (Xilinx/finn-base#29) for the PRs following in this series: [here_finnbase](https://github.com/Xilinx/finn/blob/af783db8dc2a1d2e95bd569d39464b935520b6d2/docker/finn_entrypoint.sh#L15).
Besides, the FINN-hlslib commit pointer must be changed to (at least) 5c45a41a755bca534ba737e1b54ec9bbddf42a41 [here_finn_hlslib](https://github.com/Xilinx/finn/blob/af783db8dc2a1d2e95bd569d39464b935520b6d2/docker/finn_entrypoint. …
> Added ConvolutionInputGenerator1D

- src/finn/custom_op/fpgadataflow/convolutioninputgenerator.py
- tests/fpgadataflow/test_fpgadataflow_convinputgenerator.py
Added support for non-square images for the ConvolutionInputGenerator operation by extending and modifying the attributes. Note that the Im2Col node supports all kinds of convolutions (square and non-square, non-equal dilation and/or strides along different axes), while the HLS-lib is limited to a certain set only. Therefore, this operation currently only works for square input images and kernels.
Note that the extended attributes are not needed for square convolutions. However, I decided to have it for 2 reasons: 1) consistency (as the ConvolutionInputGenerator1D requires the extended set of attributes) and 2) it makes adding support for other types of non-square convolutions easier in the future (as the Im2Col/convolution_lowering support all kinds of convolutions, this means that only …
> Support for non-square images ConvolutionInputGenerator

- src/finn/custom_op/fpgadataflow/__init__.py
- src/finn/custom_op/fpgadataflow/convolutioninputgenerator.py
- src/finn/custom_op/fpgadataflow/convolutioninputgenerator1d.py
- src/finn/custom_op/fpgadataflow/fmpadding_batch.py
- src/finn/custom_op/fpgadataflow/vector_vector_activate_batch.py
- src/finn/transformation/fpgadataflow/convert_to_hls_layers.py
- tests/fpgadataflow/test_convert_to_hls_1d_conv_layer.py
- tests/fpgadataflow/test_depthwise_convolution.py
- tests/fpgadataflow/test_fpgadataflow_convinputgenerator.py
- tests/fpgadataflow/test_fpgadataflow_convinputgenerator1d.py
- tests/fpgadataflow/test_fpgadataflow_fmpadding.py
- tests/fpgadataflow/test_fpgadataflow_vvau.py
Added support for non-square convolutions in HLS transformations and added a 1D convolution test case.
This PR is part of a series of PRs. An overview of the (priority - repository - PR# - description) is given below:
1 -- finn-base -- Xilinx/finn-base#29 -- support for non-equal dilation
2 -- finn -- #320 -- compatibility with latest finn-base changes.
Note that the FINN-base commit is be changed to point to the latest commit (Xilinx/finn-base#29) for the PRs following in this series: [here_finnbase](https://github.com/Xilinx/finn/blob/af783db8dc2a1d2e95bd569d39464b935520b6d2/docker/finn_entrypoint.sh#L15).
Besides, the FINN-hlslib commit pointer must be changed to (at least) 5c45a41a755bca534ba737e1b54ec9bbddf42a41 [here_finn_hlslib](https://github.com/Xilinx/finn/blob/af783db8dc2a1d2e95 …
> Support for non-square (1D) convolutions

- src/finn/transformation/streamline/remove.py
- tests/end2end/test_end2end_mobilenet_v1.py
- tests/transformation/streamline/test_remove_identity_ops.py
Add approximation support (comparing with `np.isclose` instead of `==`) inside the `RemoveIdentityOps` transformation. The new way of exporting scaling factors in certain places in Brevitas was causing e.g. `Mul` by 0.999999965 after streamlining, which didn't get removed in the old version due to the exact comparison.
> Remove close-to-identity ops

- docker/Dockerfile.finn_ci
- docker/Dockerfile.finn_dev
- docker/finn_entrypoint.sh
- docs/finn/getting_started.rst
- run-docker.sh
Use a debfile-based installation for XRT instead of sourcing directly from host system. The previous method sometimes caused issues with library dependencies.
> Install XRT from .deb

- src/finn/builder/build_dataflow_steps.py
- src/finn/transformation/streamline/__init__.py
- src/finn/transformation/streamline/absorb.py
- src/finn/transformation/streamline/reorder.py
Adjustments to default streamlining flow:
- Move `MoveScalarLinearPastInvariants()` behind `MoveMulPastMaxPool()`
- Relax `AbsorbTransposeIntoMultiThreshold()` so it moves Transpose past MT if no second Transpose is present
- `MakeMaxPoolNHWC()` now also moves NCHW-Transpose past MaxPool
> Support MaxPool layer before conv->fc flatten

- src/finn/util/visualization.py
This PR adds support for an externally set netron `port`, either via the environment variable or as a function parameter, same for the `localhost_url`.
Additionally, I adapted the doc string from the PR #324 to adhere to the Sphinx formatting: https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html#the-sphinx-docstring-format
> Added support for externally set netron port, this resolves #365 and can close #324

- src/finn/custom_op/fpgadataflow/convolutioninputgenerator1d.py
- src/finn/qnn-data/cpp/npy2apintstream.hpp
Adds support for https://github.com/Xilinx/finn-hlslib/pull/61 by automatically selecting the optimized 1D ConvolutionInputGenerator variant.
Already covered by existing `test_convert_to_hls_1d_conv_layer`, but I had to add support for multiple pixel ("mmv") unpacking in apintstream2npy to make cppsim work.
**Depends on:** https://github.com/Xilinx/finn-hlslib/pull/61 (commit pointer will require update)
> Support for new 1D SWG in case of full SIMD unfolding

- src/finn/custom_op/fpgadataflow/streamingfclayer_batch.py
Hi,
unfortunately I had a typo in the last SIMD check, which resulted in a off by one error.
In actuality buffers with a size of 1024 are still possible as one can see in the log of the original issue here: https://forums.xilinx.com/t5/High-Level-Synthesis-HLS/ARRAY-PARTITION-COMPLETE-has-exceeded-the-threshold-1024/td-p/862145
> Fixed off by one error in SIMD check for StreamingFCLayer_Batch.

- src/finn/transformation/streamline/reorder.py
This PR fixes issues #344 , by adding support for reordering ONNX ops, which are scalar, but where the tensor is not flat.
> Fixes #344

- src/finn/custom_op/fpgadataflow/convolutioninputgenerator1d.py
- src/finn/transformation/fpgadataflow/convert_to_hls_layers.py
This PR depends on PR [76](https://github.com/Xilinx/finn-hlslib/pull/76) from FINN-hlslib.
The following 1D SWUs are supported and optimized in FINN-hlslib:
- non-dws
- regular
- stride = any
- dws
- regular
- stride = 2
The following 1D SWUs are also supported, but not optimized in FINN-hlslib:
- dws
- dilation = any
- stride = any
The following 1D SWU is not yet supported:
- non-dws
- dilation = any
> Support for optimized 1D dws SWU

- requirements.txt
protobuf 4.21 breaks onnx so freezing it as a workaround
see discussion here:
https://github.com/protocolbuffers/protobuf/issues/10051
> freeze protobuf to 3.20.1

- src/finn/transformation/fpgadataflow/create_stitched_ip.py
- src/finn/transformation/fpgadataflow/templates.py
Fixes to make VGG10 work with 2022.1, so far includes:
- Update UltraScale PS IP version from 3.3 to 3.4
- Adapt to changed AXI slave address segment naming ("Reg"->"Reg0")
- Hotfix to remove erroneous aperture that is automatically inferred by IP packager for IODMA cores and prevents address assignment of DDR_LOW and/or DDR_HIGH segments during block design creation
**Synthesis completes successfully, but the accelerator still hangs during execution. Further investigation required.**
> Hotfixes for 2022.1

- src/finn/custom_op/fpgadataflow/lookup.py
- src/finn/transformation/fpgadataflow/create_stitched_ip.py
- src/finn/transformation/fpgadataflow/insert_iodma.py
* Allow multiple AXI MM interfaces in stitched IP (now enumerated as `m_axi_gmem0, m_axi_gmem1...`)
* Fix AXI MM segment assignment for multiple AXI MM interfaces
* Add optional args to `InsertIODMA` to choose which type of IODMAs get inserted (input, output, ext weight)
* Fix bug in Lookup layer IP stitching (only expose AXI lite & MM when in external mode)
> Fixes for Lookup external mode and IODMA insertion

- src/finn/custom_op/fpgadataflow/lookup.py
- src/finn/transformation/fpgadataflow/create_stitched_ip.py
This adds a single-bit bounds violation output to lookup layer instances. These outputs should be externalized to the boundary of the stitched IP for their potential use for IRQ signalling.
> WIP: IRQ Signalling for Input Bounds Violation (to be externalized)

- docker/Dockerfile.finn
While working on another feature I ran into a bug that required a newer version of Verilator than what was available in the Ubuntu 18.04 distribution channels (which the FINN Docker is based on) provided. This PR removes the `apt-get install verilator` in the FINN Dockerfile and replaces that with a manual clone, compile and installation of Verilator at a particular version (currently 4.012).
> Clone and install particular version of Verilator

- src/finn/transformation/fpgadataflow/make_zynq_proj.py
Use the AXI HP port width defined in finn/util/basic instead of the default value (64). This reduces the input/output DMA bottleneck for UltraScale+ platforms, which support 128-bit wide AXI ports.
> ZynqBuild: use AXI port width from part map

- src/finn/transformation/streamline/absorb.py
Change order of rewiring of new Transpose node and insertion into the graph. Before the find_consumers() transform returned the newly inserted node as well and the rewiring caused the input to be wired with the output of the same node.
> [hotfix] for AbsorbTransposeIntoResize transformation

- src/finn/transformation/fpgadataflow/convert_to_hls_layers.py
The HLS layers `StreamingEltwise`, `StreamingConcat` and `AddStreams` are not meant to work on static inputs, only on dynamic ones. This PR adds a fix to avoid converting to hardware (HLS) layers if any static inputs are detected in relevant `convert_to_hls` calls.
A future consideration here might be to support converting tensors with static initializers to memory streamer components (`memstream`) with a separate `convert_to_hls` transformation.
> Skip streaming eltwise conversion if static inputs

- tests/end2end/test_end2end_bnn_pynq.py
Remove PrepareRTLSim ipstitch rtlsim test in bnn_pynq end2end tests
> [Fix] Remove obsolete transformation in end2end bnn_pynq test

- src/finn/custom_op/fpgadataflow/vectorvectoractivation.py
Removing check for `ram_style_threshold` from VVAU, which does not have this attribute.
> Fixing error in VVAU LUT estimation

- docker/Dockerfile.finn
- requirements.txt
- src/finn/util/data_packing.py
Delete check for np.str in datapacking, because aliases of built-in types in numpy are deprecated,
> Hotfix: delete numpy.str in datapacking

- src/finn/custom_op/fpgadataflow/matrixvectoractivation.py
- src/finn/custom_op/fpgadataflow/vectorvectoractivation.py
- src/finn/transformation/fpgadataflow/minimize_weight_bit_width.py
- src/finn/util/basic.py
Adding a MinimizeWeightBitWidth() transformation, which calls the weight bit width minimization functions to save on resources when a node does not have runtime writeable weights.
> Adding MinimizeWeightBitWidth() transformation

- src/finn/custom_op/fpgadataflow/streamingdatawidthconverter_batch.py
- src/finn/transformation/fpgadataflow/insert_dwc.py
- tests/fpgadataflow/test_fpgadataflow_dwc.py
This PR makes a number of fixes and improvements to data width converters (DWCs) used in FINN.
- DWCs with `impl_style=vivado` should only be used for cases where both streams have a width divisible by 8. Otherwise, 0-valued padding bits inserted by HLS will be treated as actual data. This is a limitation of the underlying AXIS IP.
- DWCs for cases where the larger stream width is not divisible by the smaller one are now handled by transparently instantiating two`impl_style=hls` DWCs in a dataflow region with an intermediate, least common multiplier-wide stream in between.
- Previously, `impl_style=vivado` DWCs were inserted by the `InsertDWC` transformation to support non-divisible stream widths. This is now handled by the `impl_style=hls` DWCs.
- The `test_fpgadataflow_dwc_rtlsim` is …
> Fix DWC impl_style=vivado and non-divisible stream width enablement

- tests/fpgadataflow/test_fpgadataflow_convinputgenerator_rtl_dynamic.py
Ensure that I/O FIFOs are created for tests for convolutions with dynamic FM sizes.
> [Hotfix] Fix test for dynamic fm dimensions

- src/finn/transformation/fpgadataflow/create_stitched_ip.py
- src/finn/transformation/fpgadataflow/insert_fifo.py
- src/finn/transformation/fpgadataflow/set_fifo_depths.py
This PR depends on/incorporates #744 
If the first node in the graph is a FIFO with `impl_style=vivado` this can cause a glitch during stitched-IP Verilator simulation (which is used for verification as well as in FIFO sizing and throughput testing) that drops the first input sample after reset. 
This PR provides a workaround by using `impl_style=rtl` for the first FIFO as part of the `InsertAndSetFIFODepths` (for simulation-style FIFO sizing) and `InsertFIFO` (for characterization-style and premade json config) transformations. An additional warning is also raised in `CreateStitchedIP` if an input FIFO with `impl_style=vivado` is detected.
> Avoid using impl_style=vivado for the input FIFO

- src/finn/builder/build_dataflow_steps.py
When the user wants to save the wavesim, the rtlsim_trace_depth needs to be extracted, moving this outside of the if/else branch.
> [Hotfix] Builder step rtlsim performance

- .pre-commit-config.yaml
Due to a recent update to `poetry`, the installation of `pre-commit` plugin `isort` fails with this error on latest `dev`:
```
maltanar@statmalt:~/sandbox/finn$ git commit -a
[INFO] Installing environment for https://github.com/PyCQA/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/maltanar/.cache/pre-commit/repob7whc6b6/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
Processing /home/maltanar/.cache/pre-commit/repob7whc6b6
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing …
```
> [Hotfix] Bump isort version to 5.12.0

- tests/util/test_build_dataflow.py
Changes were made to a dataflow step previously that causes the test of the dataflow step to fail. Further investigation into the options is needed, until then the test is expected to fail. An option may need to be added to src/finn/qnn-data/build_dataflow/dataflow_build_config.json in order for the test to pass again but more investigation is needed to determine if that is the best option. The commit in question is: 59b19dd3699426a549b25f3926716278742ad72b
Signed-off-by: Fionn O'Donohoe <fionno@xilinx.com>
> [hotfix] mark build dataflow test as xfail

- src/finn/builder/build_dataflow_config.py
- src/finn/builder/build_dataflow_steps.py
- src/finn/custom_op/fpgadataflow/matrixvectoractivation.py
- src/finn/custom_op/fpgadataflow/vectorvectoractivation.py
- src/finn/transformation/fpgadataflow/convert_to_hls_layers.py
- tests/end2end/test_end2end_bnn_pynq.py
- Updating `MinimizeAccumulatorWidth` to account for runtime-writeable weights
- Adding new builder step `step_minimize_bit_width` to default finn flows
- Moving `MinimizeAccumulatorWidth` and `MinimizeWeightBitWidth` to new builder step
- Removing `MinimizeAccumulatorWidth` from `convert_to_hls_layers`
- Adding unit test for new builder step in end2end flow
> Adding new build step and accounting for runtime writeable weights

- requirements.txt
This library was added as a Brevitas dependency here: https://github.com/Xilinx/finn/commit/e73ce9aa72783daa2d4d3ed5f2b801ca7bd1a1b7
But Brevitas has since moved on and does not require this dependency anymore: https://github.com/Xilinx/brevitas/commit/75c3e1bf9e511f0a919f4d5e4dddf14fba8b53d1
> remove unused dependency

- tests/end2end/test_end2end_bnn_pynq.py
Skip top1 validation for bnn_pynq if file doesn't exist.
> Fix to validate top1 in bnn_pynq end2end test

- tests/fpgadataflow/test_fpgadataflow_vvau.py
Remove minimization of accumulator width for vvau testing.
Since it runs tests on only one node, running the minimization automatically will result in setting the output data type to INT8 (it is the "last" node in the test graph) even if bipolar output is expected in test case.
> Fix VVAU tests

- src/finn/transformation/fpgadataflow/create_stitched_ip.py
Rewrite Stitched IP packaging (a) to clean out XCI references and (b) to generate address maps on exposed AXI-lite interfaces.
> Rework Stitched IP Packaging

- src/finn/transformation/fpgadataflow/templates.py
Avoid hard-coded versions to improve compatibility between tool versions (e.g., between UltraScale+ PS IP of 2022.2 and 2023.1).
> [Zynq build] Retrieve auxiliary IP versions from catalog

- finn-rtllib/swg/swg_common.sv
- finn-rtllib/swg/swg_pkg.sv
- finn-rtllib/swg/swg_template_axilite.v
- finn-rtllib/swg/swg_template_default.sv
- finn-rtllib/swg/swg_template_default_dynamic.sv
- finn-rtllib/swg/swg_template_parallel.sv
- src/finn/custom_op/fpgadataflow/convolutioninputgenerator_rtl.py
- src/finn/util/pyverilator.py
- tests/fpgadataflow/test_fpgadataflow_convinputgenerator_rtl_dynamic.py
When synthesizing DSWG instances with  the latest `dev` Vivado raises the following error:
```
ERROR: [Synth 8-9123] an enum variable may only be assigned the same enum typed variable or one of its values [/scratch/finn/build/code_gen_ipgen_ConvolutionInputGenerator_rtl_0_cf9bvsk5/ConvolutionInputGenerator_rtl_0_impl.sv:73]
```
This is due to a variable in the generated SystemVerilog code
```
// state and counters
typedef enum logic [2:0] {
STATE_START,
STATE_LOOP_SIMD,
STATE_LOOP_KW,
STATE_LOOP_KH,
STATE_LOOP_W,
STATE_LOOP_H
}  state_e;
state_e  State = 1; // this value of 1 is not safe to use for the enum, STATE_LOOP_SIMD should be used
```
The fix is to use the corresponding enum values (e.g. `STATE_LOOP_SIMD` instead of `1`). However, changing this in the codegen breaks the …
> Fix SV enum bug for dynamic SWG

- src/finn/transformation/fpgadataflow/create_stitched_ip.py
- Vivado IPI requires a minimum of a 4K address range for slaves
- This PR adds a tcl command to ensure that the address range is minimum 4K for AXI-lite interface ports during IP stitching
> Set axilite address range to a minimum of 4K

- src/finn/custom_op/fpgadataflow/matrixvectoractivation.py
- src/finn/custom_op/fpgadataflow/vectorvectoractivation.py
Remove outdated stream depth pragma from HLS code generation for decoupled mode in MVAU and VVAU
> Remove outdated stream depth pragma from decoupled mode

- src/finn/util/pyverilator.py
The new "swg_pkg" source was correctly added to `pyverilate_stitched_ip` but not `verilator_fifosim`.
> Hotfix: verilator_fifosim for RTL SWG component

- src/finn/qnn-data/templates/driver/driver_base.py
Pynq on alveo uses tinynumpy under the hood which has a bug when converting between tinynumpy.ndarray and numpy.ndarray. Workaround is to first convert to list and then to numpy.ndarray.
> [Driver] Workaround for pynq on alveo bug

- src/finn/qnn-data/templates/driver/driver_base.py
- src/finn/transformation/fpgadataflow/template_driver.py
- src/finn/transformation/fpgadataflow/vitis_build.py
- src/finn/util/basic.py
- src/finn/util/platforms.py
Adds support for the Alveo U55C FPGA card to FINN.
Additionally, support to choose the FPGA device to be used for execution of the synthesized design is added to the FINN driver.
> Add support for Alveo U55C cards

- docs/finn/getting_started.rst
lmk if `dev` is a better target branch
> [Docs] Fix minor typos `run_docker.sh` -> `run-docker.sh`

- docs/finn/internals.rst
- finn-rtllib/swg/swg_common.sv
- finn-rtllib/swg/swg_template_parallel.sv
- src/finn/custom_op/fpgadataflow/convolutioninputgenerator_rtl.py
- tests/fpgadataflow/test_fpgadataflow_convinputgenerator_rtl.py
Previously, full SWG SIMD parallelism (SIMD = # Channels) was required before enabling the window-parallel mode. Due to the depthwise data layout, this prevented VVAU SIMD unfolding (across the kernel dimensions) unless VVAU PE (across the channel dimension) was maxed out.
This adds support for SWG SIMD < C when the SWG is in window-parallel and depthwise mode.
**Note that the SIMD of the SWG must match the PE of the following VVAU.**
VVAU SIMD < K is supported via a normal DWC, which is inserted automatically by the compiler.
This experimental HLS DWC component was previously introduced as a workaround for this problem and should now be obsolete: https://github.com/Xilinx/finn-hlslib/pull/134
SWG SIMD < C is also allowed in the 1x1 kernel case (no matter whether `parallel_window` is set …
> [RTL SWG] Support SIMD < C in window-parallel mode

- .github/workflows/singularity-quicktest.yml
- docker/Dockerfile.finn
- docker/finn_entrypoint.sh
- docs/finn/getting_started.rst
- run-docker.sh
Extends run-docker.sh to support execution of FINN inside a Singularity environment instead of Docker. Expects the Singularity image to be pre-built (from the normal Docker image) by the user. We use a GHA in a different repo for this.
I also added some documentation to the "Getting Started" page and a GHA that tests this feature by building a Singularity container from the FINN Docker image and running quicktest inside it.
**Example usage:**
1. Set the new env var to the Singularity image (path or registry URL) you want to use:
`export FINN_SINGULARITY=oras://ghcr.io/eki-project/experiment-manager/finn_apptainer_xilinx:dev`
_(this points to a public nightly build of the official dev branch)_
1. Run `run-docker.sh` normally
> Singularity container support for run script

- finn-rtllib/swg/swg_template_wrapper.v
- finn-rtllib/swg/swg_template_wrapper_dynamic.v
- src/finn/custom_op/fpgadataflow/convolutioninputgenerator_rtl.py
- tests/fpgadataflow/test_fpgadataflow_convinputgenerator_rtl.py
Padding to multiples of 8 seems to be required not only to satisfy the AXI Stream spec, but also for correct Verilator simulation (in case SIMD=1 and signed input with bit width that is not a multiple of 8).
> Fix: Add stream padding to RTL SWG

- src/finn/custom_op/fpgadataflow/rtl/thresholding_rtl.py
- src/finn/transformation/qonnx/qonnx_activation_handlers.py
Added workaround to enable per tensor quantization based on channel dimensions, providing consistency with per channel quantization.
Depending on the quantization strategy, a single per tensor scale could be present, however the Thresholding RTL module expects a per channel scale. This patch provides a workaround by broadcasting the scale to imitate the per channel quantization strategy.
> Broadcast single threshold values along PE dimension

- src/finn/custom_op/fpgadataflow/rtl/thresholding_rtl.py
- src/finn/transformation/fpgadataflow/make_zynq_proj.py
the onnx node names were being used as the top level wrapper file name, when running Zynq builds the onnx node name are changed due to graph partitioning causing stitched IP to lose track of the wrapper file name. 
this patch will use the `top_module_name `  variable as wrapper file name instead so there is consistency between different steps of the finn flow.
> [Thresholding rtl] Update template wrapper file names to match top module name.

- src/finn/custom_op/fpgadataflow/rtl/thresholding_rtl.py
- tests/end2end/test_end2end_bnn_pynq.py
The number of thresholding steps is 2^N where N is the activation bitwidth. the created weight file should have 0 paddings if threshold values are less than required.
> [Threshold RTL] padd threshold steps based on activation bitwidth

- docker/Dockerfile.finn
- run-docker.sh
This PR expands the capability of the docker scripts to install xrt from local .deb file.
To use a local file, set the env var FINN_XRT_PATH to the path in which the .deb file lies. Be aware, that we currently assume a specific xrt deb version: `xrt_202220.2.14.354_22.04-amd64-xrt`, see here: https://github.com/Xilinx/finn/blob/dev/run-docker.sh#L89
> Enable optional xrt installation from local deb

- docker/Dockerfile.finn
- requirements.txt
The setuptools version was overwritten by the jupyter installation, so it got moved directly to the Dockerfile as last pip install command.
> Install setupstools explicitly in Dockerfile

- src/finn/custom_op/fpgadataflow/rtl/thresholding_rtl.py
Broadcasting per tensor thresholds to number of PEs for RTL Thresholding to implement per tensor quantization more efficiently.
> Optimizing resources for per tensor quantization

- src/finn/custom_op/fpgadataflow/rtl/thresholding_rtl.py
- tests/fpgadataflow/test_fpgadataflow_thresholding.py
- tests/fpgadataflow/test_fpgadataflow_thresholding_runtime.py
To enable unsigned narrow quantization with RTL Thresholding, a dummy threshold value is appended and if necessary the threshold datatype will be increased. 
The PR also extends the test cases to capture the above described scenario.
> [RTL Thresh] Enable workaround for unsigned narrow quantization

- src/finn/builder/build_dataflow_steps.py
Increases the liveness threshold for the verification step stitched_ip_rtlsim. This will provide a bit more leeway when running rtlsim and prevent the bnn-pynq models from timing out when verification is run during the build.
> Increased liveness threshold for verify_step_stitched_ip_rtlsim

- src/finn/custom_op/fpgadataflow/convolutioninputgenerator.py
Without updating the datatype attributes of the node, there might be a mismatch between tensor annotations (the actual datatype) and the type assumed by the node. This becomes an issue for example when querying the bit-width of the stream when inserting data-width converters.
> [ConvolutionInputGenerator] Make infer_node_datatype update attributes

- custom_hls/softmax.hpp
- src/finn/custom_op/fpgadataflow/hls/quantsoftmax_hls.py
- src/finn/custom_op/fpgadataflow/quantsoftmax.py
- src/finn/transformation/fpgadataflow/convert_to_hw_layers.py
- tests/fpgadataflow/test_fpgadataflow_softmax.py
This PR updates the softmax integration to include the ability to specify input and output template datatype parameters separately. 
The main changes are:
* Updated to the HLS code to enable the specification of the separate templates for input/output.
* Compiler integration to enable the inference of the output data types and appropriate codegen.
* Test updates to allow the specification of different input/output datatypes.
I have only tested the quantsoftmax node with the following:
```
tests/fpgadataflow/test_fpgadataflow_softmax.py::test_fpga_dataflow_quantsoftmax[ifm_dim0-INT8-INT8-simd4-hls] PASSED
tests/fpgadataflow/test_fpgadataflow_softmax.py::test_fpga_dataflow_quantsoftmax[ifm_dim1-INT8-INT8-simd4-hls] PASSED
```
> Separate Input/Output datatype template parameters

- src/finn/transformation/fpgadataflow/convert_to_hw_layers.py
- src/finn/transformation/qonnx/qonnx_activation_handlers.py
This PR enables four previously not supported scenarios:
- When the global input tensor directly gets split, the compiler will now add a `DuplicateStreams` at that point when calling transformations from conversion to hw
- When the second input to a MatMul is not constant, this MatMul will be skipped during conversion and no error will be thrown.
- Previously an Add node of two streams was converted to the `AddStreams` node, it is now also possible to convert to a `StreamingEltwise` Add node.
- Previously when having a per tensor quantization, in the QONNX to FINN-ONNX conversion, the threshold array was broadcasted to the number of channels. This is now skipped and instead the per tensor quantization gets passed to the compiler for further processing.
> Update convert to hw transformation and qonnx to finn-onnx conversion

- docs/finn/faq.rst
- notebooks/end2end_example/cybersecurity/3-build-accelerator-with-finn.ipynb
finn-base seems to be deprecated and the pointed-to files now have equivalents in the finn repo.
> Update links to finn-base repo

- src/finn/transformation/fpgadataflow/insert_dwc.py
- src/finn/transformation/fpgadataflow/insert_fifo.py
Before, the onnx tensor data type wasn't preserved and defaulted to float. While the FINN dtype was preserved (so no errors in the resulting hw), this could lead to errors for the executability of an onnx graph after the `InsertFIFO` transformation, see https://github.com/Xilinx/finn/issues/1113
This PR contains changes to keep the onnx tensor dtype when inserting FIFOs.
> Preserve onnx tensor dtype when inserting FIFOs

- src/finn/transformation/fpgadataflow/convert_to_hw_layers.py
- src/finn/transformation/fpgadataflow/insert_fifo.py
- src/finn/transformation/streamline/reorder.py
- The MoveOpPastFork() transformation is more flexible because it uses deepcopies of an original node (the get_attrs_fxn parameter is not needed anymore)
- Some transformations (MoveScalarLinearPastInvariants, MakeMaxPoolNHWC, MakeScaleResizeNHWC) are fixed to check whether the node to be moved is a fork node, in which case the MoveOpPastFork would be called
- InferDuplicateStreamsLayer() transform in [src/finn/transformation/fpgadataflow/convert_to_hw_layers.py](https://github.com/Xilinx/finn/compare/dev...mdanilow:finn:feature/split_and_concat?expand=1#diff-a331fda12d6897bb8da38d2237c9a4c24df8eb8e095bde550f400d2a6a2e692f) is fixed and every output of a fork node is checked (the transform used to be applying the transform just for the first output of a node)
- InsertFIFO() transform in …
> Fixes for branched structures

- tutorials/fpga_flow/README.md
- tutorials/fpga_flow/folding_config.json
Update the folding configuration to work with latest FINN (renaming of nodes).
This PR solves: Issue https://github.com/Xilinx/finn/issues/1211
> Update folding configuration for FPGA flow tutorial

- run-docker.sh
This enables passing arguments to custom build scripts. e.g. with a build script called `test_args.py` containing:
```python
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('filename')           # positional argument
parser.add_argument('-c', '--count')      # option that takes a value
parser.add_argument('-v', '--verbose',
action='store_true')  # on/off flag
args = parser.parse_args()
print(f"{args.filename=} | {args.count=} | {args.verbose=}")
```
Can now pass in arguments via run-docker:
```bash
./run-docker.sh build_custom .. test_args abc -c 12 -v
...
args.filename='abc' | args.count='12' | args.verbose=True
The program finished and will be restarted
```
> [Infra] support passing arguments to build_custom flow

- run-docker.sh
See https://adaptivesupport.amd.com/s/article/63253?language=en_US
This issue occurs frequently for users with slow filesystems, such as for us, during the last FINN tutorial, or here: https://github.com/Xilinx/finn/issues/1215
I propose to add the workaround permanently to the Docker Container.
> [Container] Apply workaround for running multiple parallel Vivado instances

- finn-rtllib/thresholding/hdl/thresholding_axi.sv
- finn-rtllib/thresholding/sim/thresholding_axi_tb.sv
As with the other AXI wrappers of RTL components, drive the full-byte AXI-Stream extension to zero.
> Driving AXI bus padding to zero.

- src/finn/custom_op/fpgadataflow/hlsbackend.py
- src/finn/custom_op/fpgadataflow/templates.py
This PR contains changes to enable HLS custom ops to run cppsim with the new hls::vector interface instead of the packed datatype interface most finn-hlslib components currently have. The goal is to have the packed datatype and the new one provided in parallel and when all nodes use the new interface, deprecate the old one. Please note, that this mainly means changes to cppsim, the resulting interface of the HW is identical between the two methods.
Thanks to @mdanilow for his contributions to this PR!
Currently, the `cpp_interface` defaults to `"packed"`. When adding new HLS components with hls_vector interface, please overwrite that node attribute in the HLS custom operator: e.g., 
`my_attrs.update({"cpp_interface": ("s", False, "hls_vector", {"hls_vector"})})`. Make sure that this is …
> Infrastructure to incorporate components with hls::vector interface

- tests/brevitas/test_brevitas_fc.py
- tests/transformation/streamline/test_streamline_cnv.py
- tests/transformation/streamline/test_streamline_fc.py
Prevent annoying creation of empty temporary build directories during test discovery.
> Fix build dir creation for tests

- notebooks/end2end_example/bnn-pynq/cnv_end2end_example.ipynb
- notebooks/end2end_example/bnn-pynq/tfc_end2end_example.ipynb
- src/finn/builder/build_dataflow_steps.py
- tests/end2end/test_end2end_bnn_pynq.py
Replace distutil copy_tree with shutil copytree for two reasons:
1. It is deprecated
2. I ran into this obscure bug, which does not happen with copytree: https://bugs.python.org/issue22132
> Fix: Replace distutil copy_tree with shutil

- docker/jenkins/Jenkinsfile
Fixed hw_deployment_* build artifacts find and copy mechanism.
Added pytest parallel flag to fpgadataflow, making use of the already existing jenkins env variable "NUM_PYTEST_WORKERS"
Jenkins currently running, job 199
> Jenkinsfile updates

- tests/brevitas/test_brevitas_avg_pool_export.py
- tests/brevitas/test_brevitas_cnv.py
- tests/brevitas/test_brevitas_debug.py
- tests/brevitas/test_brevitas_deconv.py
- tests/brevitas/test_brevitas_non_scaled_quanthardtanh_export.py
- tests/brevitas/test_brevitas_qconv2d.py
- tests/brevitas/test_brevitas_qlinear.py
- tests/brevitas/test_brevitas_relu_act_export.py
- tests/brevitas/test_brevitas_scaled_qhardtanh_export.py
- tests/brevitas/test_brevitas_selu_act_export.py
- tests/end2end/test_end2end_bnn_pynq.py
- tests/end2end/test_end2end_cybsec_mlp.py
- tests/end2end/test_end2end_mobilenet_v1.py
- tests/end2end/test_ext_weights.py
- tests/notebooks/test_jupyter_notebooks.py
For the FINN+ CI we want to speed up the test suite.
Previously, the test suite was parallelizable only with the pytest-xdist `--dist loadfile` scheduler, because some tests assume all tests within the same file are run in-order or at least not in parallel.
This refactors the offending tests that I found (except end2end tests for now, which really depend on each other) so that we can use a better scheduler (`--dist worksteal`) for most of the test suite.
> Fix: Make Test Suite Parallelizable

- finn-rtllib/thresholding/hdl/thresholding.sv
With this PR, we're preventing Vivado from losing the RAM_STYLE attribute for the RTL Thresholding component.
> Prevent Vivado from losing RAM_STYLE attribute during synthesis.

- src/finn/custom_op/fpgadataflow/matrixvectoractivation.py
- src/finn/custom_op/fpgadataflow/vectorvectoractivation.py
Small bugfix for accumulator sizing of MVU and VVUs with runtime-writable weights, old `max(max(upper_range), max(upper_range))` was probably a copy paste bug.
> [MVU,VVU] fix bug in datatype-bound accumulator sizing

- run-docker.sh
Hi there,
The script `run-docker.sh` is currently broken for Singularity. The command generated contains unwanted quotes. See for example:
```
singularity exec "--env "SHELL=/bin/bash "--pwd "/lustre/home/nx08/nx08/s2081362-2/Software/finn "-B "/lustre/home/nx08/nx08/s2081362-2/Software/finn:/lustre/home/nx08/nx08/s2081362-2/Software/finn "-B "/tmp/finn_dev_s2081362-2:/tmp/finn_dev_s2081362-2 "--env "FINN_BUILD_DIR=/tmp/finn_dev_s2081362-2 " ...
```
This patch fixes the script so that FINN can be used in Singularity.
> Fix script to launch Singularity container

- finn-rtllib/thresholding/hdl/thresholding.sv
- finn-rtllib/thresholding/hdl/thresholding_axi.sv
This PR makes sure that threshold configuration via the designated 32-bit AXI-lite interface also works for datatypes that require address folding.
> Fixing address width computation in thresholding_axi.

- src/finn/qnn-data/templates/driver/driver_base.py
Added 64-bit address support when setting up the DMAs in the driver template file to enable compatibility with pynq v3.1 and xrt 2.17. 
Tested running multiple finn-examples with pynq v3.1 on the AUP-ZU3 board and running the tfc-w1a1-mnist example with pynq 3.0.1 on the ZCU104 board.
> Support 64-bit buffer addresses

- src/finn/custom_op/fpgadataflow/streamingfifo.py
- Default to `depth` node attribute or raise exception when RTL layer specific parameters are accessed for StreamingFIFO
> Accessing adjusted depth and impl style only when FIFO in RTL layer format

- src/finn/__init__.py
- src/finn/util/basic.py
Adds simple auto-detection of `FINN_ROOT` and `FINN_DEPS_DIR` environment variables if not set. This helps facilitate container-less use of FINN without any disruption to the existing docker flow
> Auto-detect key env vars
