src/finn/core/modelwrapper.py
src/finn/core/onnx_exec.py
src/finn/transformation/insert_topk.py
tests/transformation/test_topk_insert.py

Transformation to insert a top-k node at the output of graph

---

src/finn/custom_op/fpgadataflow/globalaccpool_batch.py
src/finn/custom_op/multithreshold.py
src/finn/custom_op/registry.py
tests/custom_op/test_multithreshold.py
tests/fpgadataflow/test_fpgadataflow_globalaccpool.py

Corresponds to AccPool_Batch finn-hls function. The "Global" prefix better expresses the functionality and the close relationship with GlobalAveragePool.
Fixes #76

Implemented GlobalAccPool HLS Op

---

src/finn/custom_op/fpgadataflow/labelselect_batch.py
src/finn/custom_op/registry.py
src/finn/util/test.py
tests/fpgadataflow/test_fpgadataflow_labelselect.py

Fixes #74 
Added a utility function to test.py as it will probably be useful in multiple tests.

Implemented LabelSelect (TopK) HLS Op

---

src/finn/custom_op/fpgadataflow/__init__.py
src/finn/custom_op/fpgadataflow/addstreams_batch.py
src/finn/custom_op/registry.py
tests/fpgadataflow/test_fpgadataflow_addstreams.py

Required for elementwise addition

Added Addstreams HLS Op

---

src/finn/transformation/streamline/reorder.py
tests/transformation/test_scalar_past_eltwise.py

transform that moves scalar linear operations past eltwise add

---

.github/workflows/quicktest-dev-pr.yml
run-docker.sh

Set up a very simple GitHub Actions flow so that any incoming PRs against dev are tested using the `quicktest` test suite (that is, non-Vivado non-slow tests). This will make it easier to deal with a larger volume of PRs.

Run quicktest with GitHub Actions on PR

---

src/finn/custom_op/fpgadataflow/thresholding_batch.py
src/finn/custom_op/registry.py
src/finn/transformation/fpgadataflow/convert_to_hls_layers.py
tests/fpgadataflow/test_convert_to_hls_layers_cnv.py
tests/fpgadataflow/test_fpgadataflow_thresholding.py

Implements a HLS Op that directly maps to MultiThresholds, and can therefore implement any activation. Fixes #77 by extension.

Implemented standalone Thresholding HLS Op

---

src/finn/custom_op/fpgadataflow/sameresize_batch.py
src/finn/custom_op/registry.py
tests/fpgadataflow/test_fpgadataflow_sameresize.py

Introduce the SameResize_Batch HLSCustomOp for convolution padding. This PR was accidentally merged before undergoing review, now with the necessary changes.

SameResize_batch HLSCustomOp

---

docker/finn_entrypoint.sh
run-docker.sh

Added optional paths to Vitis installation and DSA installation. These are required if users want to build with Vitis.

Modified docker-related scripts to enable Vitis in the container

---

src/finn/custom_op/fpgadataflow/duplicatestreams_batch.py
tests/fpgadataflow/test_fpgadataflow_duplicatestreams.py

fixed `make_shape_compatible_op` for `DuplicateStreams_Batch`

[HLSCustomOp] Fix inferShapes for InferDuplicateStreamsLayer

---

src/finn/custom_op/streamingdataflowpartition.py
src/finn/transformation/fpgadataflow/create_dataflow_partition.py
src/finn/transformation/fpgadataflow/insert_fifo.py
src/finn/transformation/fpgadataflow/insert_iodma.py
src/finn/transformation/fpgadataflow/insert_tlastmarker.py

I believe this should have no dependency on any other PR, but would merge it after my previous ones just to be sure

Updated multiple build-related transforms to recognize IODMAs and nonlinear graphs

---

src/finn/util/vcd.py

Hi,
this PR would resolve the issues #205 .
I also added a bit of documentation to the function.
Cheers,
Hendrik

Fixes Xilinx/finn#205

---

.gitignore
docker/Dockerfile.finn_ci
docker/Dockerfile.finn_dev
docker/finn_entrypoint.sh
finn-rtllib/memstream/component.xml
src/finn/analysis/fpgadataflow/post_synth_res.py
src/finn/core/onnx_exec.py
src/finn/core/remote_exec.py
src/finn/custom_op/fpgadataflow/iodma.py
src/finn/custom_op/fpgadataflow/templates.py
src/finn/custom_op/streamingdataflowpartition.py
src/finn/transformation/fpgadataflow/annotate_resources.py
src/finn/transformation/fpgadataflow/create_dataflow_partition.py
src/finn/transformation/fpgadataflow/create_stitched_ip.py
src/finn/transformation/fpgadataflow/insert_fifo.py
src/finn/transformation/fpgadataflow/insert_iodma.py
src/finn/transformation/fpgadataflow/make_pynq_driver.py
src/finn/transformation/fpgadataflow/make_pynq_proj.py
src/finn/transformation/fpgadataflow/make_zynq_proj.py
src/finn/transformation/fpgadataflow/templates.py
src/finn/transformation/fpgadataflow/vitis_build.py
tests/end2end/test_zynqbuild_end2end_cnv_w1a1.py
tests/end2end/test_zynqbuild_end2end_tfc_w1a1.py
tests/end2end/test_zynqbuild_end2end_tfc_w2a2.py
tests/fpgadataflow/test_fpgadataflow_ipstitch.py

Adds capability to build for Zynq using a custom shell, using IODMAs similar to how Vitis builds work.
Depends on PRs up to #188.

Added transform for building with custom (non-Pynq) Zynq shell

---

src/finn/transformation/fpgadataflow/vitis_build.py

Add optional Vitis debug infrastructure

---

notebooks/end2end_example/cybersecurity/1-train-mlp-with-brevitas.ipynb
notebooks/end2end_example/cybersecurity/2-export-to-finn-and-verify.ipynb
notebooks/end2end_example/cybersecurity/3-build-accelerator-with-finn.ipynb

Hi,
here are the changes, which I would suggest after testing the three notebooks.
All the best,
Hendrik

Added suggestions form testing

---

docs/finn/faq.rst
docs/finn/index.rst

Added a Frequently Asked Questions documentation page based on the most generic questions in the [FINN-Gitter](https://gitter.im/xilinx-finn/community) community forum. More Q&As will be added in the future.

[Docs ] Add FAQ page to the Documentation

---

docker/Dockerfile.finn_dev
src/finn/transformation/streamline/__init__.py
src/finn/transformation/streamline/reorder.py
src/finn/util/visualization.py
tests/transformation/streamline/test_move_mul_past_maxpool.py

**Issue:** 
Netron visualization does not work due to change in how Netron takes parameters for the address.
**Solution:**
Change parameters passed to Netron from two being distinct to a tuple of parameters.

Change in how Netron takes parameters

---

src/finn/transformation/fpgadataflow/make_zynq_proj.py
src/finn/transformation/fpgadataflow/templates.py
tests/end2end/test_end2end_bnn_pynq.py

Set the proper BD address segment range based on the exposed address width.

Fix AXI addressing for large runtime-writable weight arrays

---

src/finn/transformation/streamline/reorder.py
tests/transformation/streamline/test_move_identical_op_past_join_op.py

[reorder]: added a new transformation MoveIdenticalOpPastJoinOp.
[test_move_identical_op_past_join_op]: added test case for new transformation.

Added MoveIdenticalOpPastJoinOp transformation

---

src/finn/transformation/fpgadataflow/make_pynq_driver.py

Problem: The generated driver did not use the actual folded input/output shapes, so the data was packed incorrectly in cases where padding to byte multiples is needed (e.g. the cybersecurity example with SIMD=15 in the first layer).
Solution: Extract the folded shapes from the first node after/before the input/output IODMAs. This simple fix allows for the MakePYNQDriver transformation to be called before or after IODMA/SDP creation, so it should be compatible with PR #238.

Fix incorrect shapes for data packing in Pynq driver

---

docker/Dockerfile.finn_ci
docker/quicktest.sh
docs/finn/getting_started.rst
notebooks/end2end_example/bnn-pynq/cnv_end2end_example.ipynb
notebooks/end2end_example/bnn-pynq/tfc_end2end_example.ipynb
setup.cfg
src/finn/builder/build_dataflow_config.py
src/finn/custom_op/fpgadataflow/addstreams_batch.py
src/finn/custom_op/fpgadataflow/duplicatestreams_batch.py
src/finn/custom_op/fpgadataflow/hlscustomop.py
src/finn/custom_op/fpgadataflow/iodma.py
src/finn/custom_op/fpgadataflow/streamingdatawidthconverter_batch.py
src/finn/custom_op/fpgadataflow/streamingfclayer_batch.py
src/finn/custom_op/fpgadataflow/streamingfifo.py
src/finn/custom_op/fpgadataflow/thresholding_batch.py
src/finn/custom_op/fpgadataflow/tlastmarker.py
src/finn/qnn-data/templates/driver/driver_base.py
src/finn/qnn-data/test_ext_weights/tfc-w1a1-extw.json
src/finn/transformation/fpgadataflow/create_stitched_ip.py
src/finn/transformation/fpgadataflow/insert_dwc.py
src/finn/transformation/fpgadataflow/insert_iodma.py
src/finn/transformation/fpgadataflow/make_deployment.py
src/finn/transformation/fpgadataflow/make_pynq_driver.py
src/finn/transformation/fpgadataflow/make_zynq_proj.py
src/finn/transformation/fpgadataflow/template_driver.py
src/finn/transformation/fpgadataflow/vitis_build.py
tests/end2end/test_end2end_access_board.py
tests/end2end/test_end2end_cybsec_mlp.py
tests/end2end/test_ext_weights.py

Make the linking step optional with an argument passed to VitisBuild

Make linking optional

---

docker/finn_entrypoint.sh
src/finn/transformation/fpgadataflow/templates.py

Hi,
this now also includes the known-good commit for the Avnet repository, so such issues shouldn't happen in the future.

Fixes #341

---

notebooks/end2end_example/bnn-pynq/cnv_end2end_example.ipynb

- Add some info about preprocessing and postprocessing
- Update broken links to finn example files directory

Minor updates to CNV notebook

---

.github/workflows/docker-image.yml
docker/Dockerfile.finn
src/finn/transformation/fpgadataflow/synth_ooc.py

Changes from #365 plus linting, opened as separate PR to avoid overwriting @umav1511 dev branch.

 Updates to out-of-context synth

---

.github/workflows/docker-image.yml
docker/Dockerfile.finn
docs/finn/getting_started.rst
run-docker.sh
src/finn/transformation/fpgadataflow/synth_ooc.py

- Fixes a bug where GPUs were not being autodetected
- Adds the ability to select GPUs based on `NVIDIA_VISIBLE_DEVICES`
- Update docs

Add ability to select GPUs

---

src/finn/custom_op/fpgadataflow/streamingfclayer_batch.py

Hi,
the added SIMD check can be found in line 1015 to 1024.
The pre-commit hooks also changed some of the other lines.

Added SIMD requirement to StreamingFCLayer_Batch

---

src/finn/transformation/streamline/absorb.py

Fixed issue with AbsorbTransposeIntoMultiThreshold transformation applied on non-linear graphs.

AbsorbTransposeIntoMultiThreshold for non-linear graphs

---

.pre-commit-config.yaml
requirements.txt
src/finn/builder/build_dataflow_config.py
src/finn/builder/build_dataflow_steps.py
src/finn/custom_op/fpgadataflow/streamingfclayer_batch.py
src/finn/custom_op/fpgadataflow/vector_vector_activate_batch.py
src/finn/transformation/fpgadataflow/set_fifo_depths.py
src/finn/transformation/qonnx/infer_quant_avg_pool_2d.py
src/finn/transformation/qonnx/qonnx_activation_handlers.py
tests/end2end/test_end2end_bnn_pynq.py
tests/fpgadataflow/test_fpgadataflow_vvau.py
tests/fpgadataflow/test_set_folding.py

Changed git:// to https:// in repo URL since git:// is not supported anymore.
Thanks a lot to @HPC-Ken for helping out :)

Changes to pre-commit YAML file

---

src/finn/custom_op/fpgadataflow/streamingmaxpool_batch.py
src/finn/transformation/fpgadataflow/convert_to_hls_layers.py
src/finn/transformation/streamline/reorder.py
tests/fpgadataflow/test_layer_streaming_maxpool_batch.py
tests/transformation/streamline/test_maxpool_nhwc.py

This PR depends on:
- FINN: PR [#542](https://github.com/Xilinx/finn/pull/542)
- FINN-base: PR [#56](https://github.com/Xilinx/finn-base/pull/56)
- FINN-hlslib: PR [#78](https://github.com/Xilinx/finn-hlslib/pull/78)

Support for ceil mode MaxPool layer

---

src/finn/core/throughput_test.py
src/finn/qnn-data/templates/driver/driver_base.py
src/finn/transformation/fpgadataflow/make_pynq_driver.py
tests/end2end/test_end2end_bnn_pynq.py

* Add missing `__init__.py` files to generated PYNQ driver
* Fix bandwidth units from Mb/s to MB/s (bytes and not bits)

Fixes to driver and units

---

.github/workflows/pre-commit.yml

Signed-off-by: Fionn O'Donohoe <fionno@xilinx.com>

[actions] Update precommit version to work with Act

---

src/finn/custom_op/fpgadataflow/vectorvectoractivation.py

add the missing helper function to VVAU

VVAU: add weightstream width helper

---

src/finn/transformation/fpgadataflow/insert_iodma.py

Hotfix to make the new fifo sizing and insertion work with nodes (MVAUs & VVAUs) with external weights

[Transform] Extend inFIFODepths for extw nodes

---

src/finn/custom_op/fpgadataflow/streamingfifo.py

[CustomOp] Add dtype functions to StreamingFIFO. This solves issue #665 .

Fix get dtype functions for StreamingFIFO

---

src/finn/util/test.py

[Util] Change np.int to np.int_

Hotfix: Updating code to use correct numpy types

---

notebooks/end2end_example/bnn-pynq/cnv_end2end_example.ipynb
notebooks/end2end_example/bnn-pynq/tfc_end2end_example.ipynb
src/finn/qnn-data/build_dataflow/dataflow_build_config.json
tests/util/test_build_dataflow.py

Fix known issues for release:
- End2end notebooks: reference correct modelfile
- Fix build_dataflow test by enabling python rtlsim

Fix known issues for release

---

tests/brevitas/test_brevitas_relu_act_export.py

Update export tests for Brevitas QuantReLU layer.

Update QuantReLU export test

---

notebooks/end2end_example/bnn-pynq/cnv_end2end_example.ipynb

Changed from "Summmmary" to "Summary"

Fixed Summary Typo

---

tests/end2end/test_end2end_cybsec_mlp.py

Cybersecurity MLP test needed to be changed to reflect the current updated resource estimations in the MVAU.

Update resource estimates in cybsec test

---

.isort.cfg
docker/quicktest.sh
notebooks/end2end_example/bnn-pynq/cnv_end2end_example.ipynb
requirements.txt
run-docker.sh
setup.cfg
setup.py
src/finn/transformation/fpgadataflow/create_stitched_ip.py
src/finn/transformation/fpgadataflow/make_pynq_driver.py
src/finn/util/pyverilator.py
src/finn/util/test.py
tests/brevitas/test_brevitas_cnv.py
tests/end2end/test_end2end_cybsec_mlp.py
tests/end2end/test_ext_weights.py
tests/fpgadataflow/test_convert_to_hls_layers_cnv.py
tests/transformation/streamline/test_streamline_cnv.py
tests/transformation/test_batchnorm_to_affine_bnn_pynq.py
tests/transformation/test_qonnx_to_finn.py
tests/util/test_build_dataflow.py

- Change code to use alternatives to pkg_resources
- Update setuptools version

Deprecate pkg_resources

---

docker/jenkins/Jenkinsfile_CI

Target finn-build machine if available, otherwise target built-in node

[Jenkins] Add node label to Jenkinsfile_CI to target specific machine if available

---

tests/fpgadataflow/test_fpgadataflow_lookup.py
tests/fpgadataflow/test_fpgadataflow_upsampler.py

- Update upsampler & lookup tests to use QONNX export instead of FINN-ONNX export

[Tests] Update export to qonnx export

---

.readthedocs.yaml
docs/requirements.txt
requirements.txt

Adjust configuration file and python requirements for rtd website

Fix readthedocs setup

---

fetch-repos.sh
run-docker.sh

Add optional env var to skip board download 

---

src/finn/analysis/fpgadataflow/res_estimation.py
src/finn/custom_op/fpgadataflow/hls/__init__.py
src/finn/custom_op/fpgadataflow/hls/matrixvectoractivation_hls.py
src/finn/custom_op/fpgadataflow/hls/vectorvectoractivation_hls.py
src/finn/custom_op/fpgadataflow/hlsbackend.py
src/finn/custom_op/fpgadataflow/matrixvectoractivation.py
src/finn/custom_op/fpgadataflow/vectorvectoractivation.py
src/finn/transformation/fpgadataflow/convert_to_hw_layers.py
src/finn/transformation/fpgadataflow/create_stitched_ip.py
src/finn/transformation/fpgadataflow/floorplan.py
src/finn/transformation/fpgadataflow/insert_dwc.py
src/finn/transformation/fpgadataflow/insert_iodma.py
src/finn/transformation/fpgadataflow/insert_tlastmarker.py
src/finn/transformation/fpgadataflow/make_pynq_driver.py
src/finn/transformation/fpgadataflow/make_zynq_proj.py
src/finn/transformation/fpgadataflow/set_fifo_depths.py
src/finn/transformation/fpgadataflow/set_folding.py
tests/fpgadataflow/test_fpgadataflow_mvau.py
tests/fpgadataflow/test_fpgadataflow_vvau.py

This PR introduces the refactoring of the MVAU and VVAU layers into an abstract HW custom-op and specialized HLS custom-op.
No new test cases are introduced, but the existing MVAU/VVAU fpgadataflow tests are extended. Please refer to:
1. https://github.com/Xilinx/finn/blob/dev/tests/fpgadataflow/test_fpgadataflow_mvau.py
2. https://github.com/Xilinx/finn/blob/dev/tests/fpgadataflow/test_fpgadataflow_vvau.py

Refactoring of HLS MVAU/VVAU

---

src/finn/analysis/fpgadataflow/res_estimation.py
src/finn/custom_op/fpgadataflow/hls/__init__.py
src/finn/custom_op/fpgadataflow/hls/matrixvectoractivation_hls.py
src/finn/custom_op/fpgadataflow/hls/vectorvectoractivation_hls.py
src/finn/custom_op/fpgadataflow/hlsbackend.py
src/finn/custom_op/fpgadataflow/matrixvectoractivation.py
src/finn/custom_op/fpgadataflow/vectorvectoractivation.py
src/finn/transformation/fpgadataflow/convert_to_hw_layers.py
src/finn/transformation/fpgadataflow/create_stitched_ip.py
src/finn/transformation/fpgadataflow/floorplan.py
src/finn/transformation/fpgadataflow/insert_dwc.py
src/finn/transformation/fpgadataflow/insert_iodma.py
src/finn/transformation/fpgadataflow/insert_tlastmarker.py
src/finn/transformation/fpgadataflow/make_pynq_driver.py
src/finn/transformation/fpgadataflow/make_zynq_proj.py
src/finn/transformation/fpgadataflow/set_fifo_depths.py
src/finn/transformation/fpgadataflow/set_folding.py
tests/fpgadataflow/test_fpgadataflow_mvau.py
tests/fpgadataflow/test_fpgadataflow_vvau.py

This PR introduces the refactoring of the MVAU and VVAU layers into an abstract HW custom-op and specialized RTL custom-op.
---
**Depends on:**
1. Refactoring of HLS MVAU/VVAU: https://github.com/Xilinx/finn/pull/971

Refactoring of RTL MVAU/VVAU

---

src/finn/custom_op/fpgadataflow/rtl/thresholding_rtl.py

binary-search thresholding RTL expects 2^N-1 thresholds, however, Brevitas implements signed activations using "narrow range" which drops one quantized values to keep the symmetry around 0. to get around this, we prepend a dummy threshold and offset the bias by -1.

[Thresholding RTL] Prepend dummy threshold for narrow range quantization

---

src/finn/custom_op/fpgadataflow/matrixvectoractivation.py

Ensure shape is compatible in execution function. This PR addresses: https://github.com/Xilinx/finn/issues/1109
There is some more testing required before it gets merged.

Extension of execution function of MVAU HW op

---

src/finn/transformation/fpgadataflow/specialize_layers.py

Adding the ability to grab specialised layers from a plugin module by using the nodes domain rather that just searching the FINN module. This is in a similar fashion to how QONNX builds it's registry.

custom/transformer: Search plugin modules when performing the SpecializeLayer transformation.

---

src/finn/builder/build_dataflow_config.py
src/finn/util/basic.py
tests/fpgadataflow/test_fifosizing.py

This PR updates the ALVEO part map to include the V80.

Add V80 to Alveo part_map

---

src/finn/transformation/fpgadataflow/set_fifo_depths.py
tests/fpgadataflow/test_fifosizing.py

This PR allows multi io for xsi-based fifo sizing, thanks and kudos to @maltanar !

Multi IO FIFO sizing - xsi-based

---

src/finn/transformation/fpgadataflow/convert_to_hw_layers.py

Remove ParamNode from InferFinnLoop; retain param inputs and initializers to loopbody

---

src/finn/custom_op/fpgadataflow/rtl/matrixvectoractivation_rtl.py

[RTL MVAU] Fix indentation in rtlsim execution

---

finn_xsi/finn_xsi/sim_engine.py

This PR revises the driving of the simulation. It abolishes the update of inputs with the falling edge of the main clock in favor of their update close after its rising edge. This behavior avoids interfering with faster clocks in the design that have earlier active clock edges and should not see stale inputs.

Revised signal driving within clock cycle.

---

src/finn/custom_op/fpgadataflow/hls/matrixvectoractivation_hls.py
src/finn/custom_op/fpgadataflow/matrixvectoractivation.py
src/finn/custom_op/fpgadataflow/rtl/matrixvectoractivation_rtl.py

Differentiate between exposed weight width and stream width between dyn load and MVAU.

Update dynamic MVAU stream width

---

finn-rtllib/mlo/infrastructure/create_index0_stream_from_input.sv
finn-rtllib/mlo/infrastructure/create_index0_stream_from_input_tb.sv
finn-rtllib/mlo/infrastructure/mux_in.sv
finn-rtllib/mlo/infrastructure/mux_out.sv
finn-rtllib/mlo/loop_control.sv
finn-rtllib/mlo/loop_control_wrapper.v
src/finn/builder/build_dataflow_steps.py
src/finn/custom_op/fpgadataflow/rtl/finn_loop.py
tests/end2end/test_end2end_mlo.py

- Sync work on both branches to then remove `feature/loop_op_xsi`

Merge loop op xsi work into general loop op branch

---

docs/finn/internals.rst
src/finn/custom_op/fpgadataflow/hls/upsampler_hls.py
src/finn/custom_op/fpgadataflow/upsampler.py
src/finn/transformation/fpgadataflow/convert_to_hw_layers.py
tests/fpgadataflow/test_fpgadataflow_upsampler.py

- This PR switches the upsample hlslib function to the current implementation on the finn-hlslib dev branch with the new updated interface (hls stream of hls vector)
- Thanks to @mdanilow for his initial FINN integration on his fork that enabled this PR

Update used finn-hlslib function for Upsampling

---

src/finn/custom_op/fpgadataflow/thresholding.py

Minor reorder of minimize accumulator width in thresholding to ignore non-integer inputs. This will be extended to include fixed-point inputs in the future.

Minimize thresholds only if inputs are integers
